;;; pg-propre.el --- Format and lint PostgreSQL SQL with pg_propre  -*- lexical-binding: t; -*-

;; Copyright (C) 2026  Thibaut Madelaine

;; Author: Thibaut Madelaine
;; Keywords: languages, tools
;; Homepage: https://github.com/madtibo/emacs-pg-propre
;; Package-Requires: ((emacs "26.1") (reformatter "0.3"))
;; Package-Version: 0.1

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This package integrates `pg_propre', a fast PostgreSQL SQL formatter
;; and linter, into Emacs.
;;
;; It provides:
;;
;; - `pg-propre-format-buffer' and `pg-propre-format-region' commands,
;;   plus a `pg-propre-format-on-save-mode' minor mode, all generated by
;;   the `reformatter' library.
;;
;; - `pg-propre-flymake', a Flymake backend driving `pg_propre --lint',
;;   together with `pg-propre-setup-flymake' to enable it in a buffer.
;;
;; Typical setup:
;;
;;     (add-hook 'sql-mode-hook
;;               (lambda ()
;;                 (pg-propre-format-on-save-mode)
;;                 (pg-propre-setup-flymake)
;;                 (flymake-mode)))
;;
;; `pg_propre' reads its own configuration from `.proprerc' and
;; `.editorconfig', so no extra arguments are needed by default.  Set
;; `pg-propre-args' to pass options such as a `--style' preset.

;;; Code:

(eval-when-compile
  (require 'cl-lib))
(require 'reformatter)
(require 'flymake)

(defgroup pg-propre nil
  "Format and lint PostgreSQL SQL with pg_propre."
  :group 'tools
  :link '(url-link :tag "Homepage" "https://github.com/madtibo/emacs-pg-propre"))

(defcustom pg-propre-command "pg_propre"
  "Name of, or path to, the pg_propre executable."
  :type 'string
  :group 'pg-propre)

(defcustom pg-propre-args nil
  "Extra command-line arguments passed to pg_propre when formatting.
For example, \\='(\"--style\" \"celko\") to select a style preset.
The lint backend always adds \"--lint\" and does not use this list."
  :type '(repeat string)
  :group 'pg-propre)

;;; Formatter

;;;###autoload (autoload 'pg-propre-format-buffer "pg-propre" nil t)
;;;###autoload (autoload 'pg-propre-format-region "pg-propre" nil t)
;;;###autoload (autoload 'pg-propre-format-on-save-mode "pg-propre" nil t)
(reformatter-define pg-propre-format
  :program pg-propre-command
  :args pg-propre-args
  :lighter " PgP"
  :group 'pg-propre)

;;; Flymake backend

(defconst pg-propre--diagnostic-regexp
  "^[^:]*:\\([0-9]+\\):\\([0-9]+\\): \\(error\\|warning\\): \\(.*\\)$"
  "Regexp matching one GCC-format diagnostic line from `pg_propre --lint'.
Capture groups are line, column, severity and message.")

(defun pg-propre--parse-diagnostics (output source)
  "Parse pg_propre lint OUTPUT into Flymake diagnostics for buffer SOURCE.
OUTPUT is the raw text printed by `pg_propre --lint'.  Return a list
of `flymake-make-diagnostic' objects."
  (let (diags)
    (with-temp-buffer
      (insert output)
      (goto-char (point-min))
      (while (re-search-forward pg-propre--diagnostic-regexp nil t)
        (let* ((line (string-to-number (match-string 1)))
               (col (string-to-number (match-string 2)))
               (type (if (string= (match-string 3) "error") :error :warning))
               (msg (match-string 4))
               (region (flymake-diag-region source line col)))
          (when region
            (push (flymake-make-diagnostic source (car region) (cdr region)
                                           type msg)
                  diags)))))
    (nreverse diags)))

(defvar-local pg-propre--flymake-proc nil
  "Currently running pg_propre lint process for this buffer, if any.")

;;;###autoload
(defun pg-propre-flymake (report-fn &rest _args)
  "A Flymake backend for pg_propre.
Lints the current buffer with `pg_propre --lint' and reports the
results via REPORT-FN.  Add this to `flymake-diagnostic-functions',
or call `pg-propre-setup-flymake'."
  (unless (executable-find pg-propre-command)
    (error "Cannot find pg_propre executable: %s" pg-propre-command))
  (when (process-live-p pg-propre--flymake-proc)
    (kill-process pg-propre--flymake-proc))
  (let ((source (current-buffer)))
    (save-restriction
      (widen)
      (setq pg-propre--flymake-proc
            (make-process
             :name "pg-propre-flymake" :noquery t :connection-type 'pipe
             :buffer (generate-new-buffer " *pg-propre-flymake*")
             :command (list pg-propre-command "--lint")
             :sentinel
             (lambda (proc _event)
               (when (memq (process-status proc) '(exit signal))
                 (unwind-protect
                     (if (with-current-buffer source
                           (eq proc pg-propre--flymake-proc))
                         (let ((output (with-current-buffer (process-buffer proc)
                                         (buffer-string))))
                           (funcall report-fn
                                    (pg-propre--parse-diagnostics output source)))
                       (flymake-log :warning "Canceling obsolete check %s" proc))
                   (kill-buffer (process-buffer proc)))))))
      (process-send-region pg-propre--flymake-proc (point-min) (point-max))
      (process-send-eof pg-propre--flymake-proc))))

;;;###autoload
(defun pg-propre-setup-flymake ()
  "Enable the pg_propre Flymake backend in the current buffer.
You still need to turn on `flymake-mode' to see diagnostics."
  (interactive)
  (add-hook 'flymake-diagnostic-functions #'pg-propre-flymake nil t))

(provide 'pg-propre)
;;; pg-propre.el ends here
